version: 0.0
os: linux
files:
  - source: /header.php
    destination: /var/www/html/wp-content/themes/testing/
hooks:
  BeforeInstall:
    - location: scripts/installapache.sh
      timeout: 300
      runas: root
    
    - location: scripts/startapache.sh
      runas: root
      timeout: 300
  
  AfterInstall:
    - location: scripts/restartapache.sh
      runas: root
